require('indent_blankline').setup({
    buftype_exclude = { 'terminal', 'nofile' },
    filetype_exclude = {
        'help',
        'dashboard',
        'packer',
        'man',
        'lspinfo',
        'diagnosticpopup',
        'neogitstatus',
        'NvimTree',
        'Trouble',
    },
    char = '│',
    space_char_blankline = ' ',
    show_end_of_line = true,
    show_first_indent_level = false,
    show_trailing_blankline_indent = false,
    use_treesitter = true,
    show_current_context = true,
    context_patterns = {
        'class',
        'return',
        'function',
        'method',
        '^if',
        '^while',
        'jsx_element',
        '^for',
        '^object',
        '^table',
        'block',
        'arguments',
        'if_statement',
        'else_clause',
        'jsx_element',
        'jsx_self_closing_element',
        'try_statement',
        'catch_clause',
        'import_statement',
        'operation_type',
    },
})

-- HACK: work-around for https://github.com/lukas-reineke/indent-blankline.nvim/issues/59
vim.wo.colorcolumn = '99999'
